spring.application.name=theatre-management-system
# Active profile
spring.profiles.active=dev

server.port=8080

theatre.reservation-hold-minutes=15
theatre.default-page-size=10
theatre.log-level=INFO
theatre.log-file=logs/theatre.log

# Spring logging
logging.level.root=WARN
logging.level.bg.sofia.uni.fmi.theatre=INFO